### ISSUE TITLE
modifica README

### ISSUE THREAD

**Issue by FabioZTessitore** [MarcoDaniello/Daniello#1]
prova a modificare il file README e a caricare la nuova versione

**Comment by FabioZTessitore** [comment]
difficoltà?

**Comment by MarcoDaniello** [comment]
professore quando cerco di aprire il vostro file mi fa book not found

2017-01-12 15:58 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
prova qui https://fabioztessitore.github.io/laboratorio/
